### ISSUE TITLE
panic: Failed to find environment variable with identifier: FACILITY_VALUE

### ISSUE THREAD

**Issue by fbs2016** [tozny/utils-go#66] opened 2023-02-01 12:41 UTC
Update it from github.com/tozny/utils-go v0.0.58 to github.com/tozny/utils-go v0.0.61, it reports err:
panic: Failed to find environment variable with identifier: FACILITY_VALUE

goroutine 1 [running]:
github.com/tozny/utils-go.MustGetenv({0x11a38ba, 0xe})
        /xx/go/pkg/mod/github.com/tozny/utils-go@v0.0.61/os.go:13 +0x16d
github.com/tozny/utils-go/logging.init()
        /xx/go/pkg/mod/github.com/tozny/utils-go@v0.0.61/logging/syslog_format._logging.go:108 +0xc78

**Comment by jwessel** [comment] 2023-02-02 14:04
It caused by the commit: 0e7c6ae1e37faf3aa43708e7cce1b0b7edde277c

It added a static initializer for:

var Facility = FacilityPriority(utils.MustGetenv("FACILITY_VALUE"))

I am assuming this is probably set by the server code, but this library is pulled in implicitly for the client libraries as well which is not setting the variable and causing the linked applications to crash as a result.

**Comment by rosasck** [comment] 2023-02-03 17:12
This has been fixed in the latest version

**Closed as completed by rosasck** 2023-02-03 17:12 UTC
